# .github/workflows/playwright-daily.yml
name: Run Playwright tests

on:
  push:
  pull_request:
  schedule:
    - cron: '30 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Playwright shards
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Chromium → 25% (5 tests, 2 shards)
          - browser: chromium
            shardIndex: 1
            shardTotal: 8
          - browser: chromium
            shardIndex: 2
            shardTotal: 8

          # Firefox → 25% (5 tests, 2 shards)
          - browser: firefox
            shardIndex: 3
            shardTotal: 8
          - browser: firefox
            shardIndex: 4
            shardTotal: 8

          # WebKit → 25% (5 tests, 2 shards)
          - browser: webkit
            shardIndex: 5
            shardTotal: 8
          - browser: webkit
            shardIndex: 6
            shardTotal: 8

          # Android → 10% (2 tests, 1 shard)
          - browser: 'Pixel 5'
            shardIndex: 7
            shardTotal: 8

          # iOS → 10% (2 tests, 1 shard)
          - browser: 'iPhone 13'
            shardIndex: 8
            shardTotal: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "NEW_PASSWORD=${{ secrets.NEW_PASSWORD }}" >> .env
          echo "FIRST_NAME=${{ secrets.FIRST_NAME }}" >> .env
          echo "STREET_NAME=${{ secrets.STREET_NAME }}" >> .env
          echo "CITY=${{ secrets.CITY }}" >> .env
          echo "STATE=${{ secrets.STATE }}" >> .env
          echo "COUNTRY=${{ secrets.COUNTRY }}" >> .env
          echo "ZIP_CODE=${{ secrets.ZIP_CODE }}" >> .env

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps + browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run shard ${{ matrix.shardIndex }} on ${{ matrix.browser }}
        run: npx playwright test --project="${{ matrix.browser }}" --reporter=blob --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload blob report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.browser }}-${{ matrix.shardIndex }}
          path: ./blob-report
          retention-days: 1

  merge-reports:
    name: Merge Reports
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps + browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Download all blob reports
        uses: actions/download-artifact@v4
        with:
          path: ./all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge HTML & JSON reports
        run: npx playwright merge-reports --config=playwright.config.js ./all-blob-reports

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: Playwright Test Report
          path: ./playwright-report
          retention-days: 14

      - name: Send TestDino report
        run: |
          npx --yes tdpw ./playwright-report \
            --token="${{ secrets.TESTDINO_TOKEN }}" \
            --upload-html \
            --verbose
